{% set version = "20.11.0" %}

package:
  name: isoduration
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/i/isoduration/isoduration-{{ version }}.tar.gz
    sha256: ac2f9015137935279eac671f94f89eb00584f940f5dc49462a0c4ee692ba1bd9
    folder: dist
  - url: https://github.com/bolsote/isoduration/archive/refs/tags/{{ version }}.tar.gz
    sha256: a72c92cfc3810117d2289792a39f17a0bf71a4065384ff117032fb5917e93e24
    folder: src

build:
  number: 1
  noarch: python
  script:
    - cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - arrow >=0.15.0
    - python >={{ python_min }}

test:
  source_files:
    - src/tests
  imports:
    - isoduration
    - isoduration.formatter
  commands:
    - pip check
    - cd src/tests 
    - coverage run --source=isoduration --branch -m pytest -vv --tb=long --color=yes 
    - coverage report --show-missing --skip-covered --fail-under=98
  requires:
    - coverage
    - hypothesis
    - isodate
    - pip
    - pytest
    - pytest-benchmark
    - python {{ python_min }}

about:
  home: https://github.com/bolsote/isoduration
  summary: Operations with ISO 8601 durations
  license: MIT
  license_file: dist/LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
